//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildscreenLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalImage
    {
        public int Id { get; set; }
        public Nullable<int> Animal_Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string SourceSystem { get; set; }
        public Nullable<int> Upvotes { get; set; }
        public Nullable<int> Downvotes { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
